### PR TITLE
Fixes #215: Better error message on missing IP address

### LINKED ISSUE #215: Mock for IP address assignment doesn't work
## Describe the bug

When using WaitForNonLocalIP after VM start the IP never gets assigned

## To Reproduce

Please see: https://github.com/oVirt/terraform-provider-ovirt/pull/435

### PR DESCRIPTION
**Pull request by janosdebugs**
## Please describe the change you are making

This change adds an explicit error message when a required IP address is not found that checks if the VM has a NIC attached and warns the user if that is not the case.

## Are you the owner of the code you are sending in, or do you have permission of the owner?

Yes

## The code will be published under the BSD 3 clause license. Have you read and understood this license?

Yes

### CODE REVIEW

File: vm_ip_wait.go [hunk 1]
```diff
@@ -31,10 +32,34 @@ func waitForIPAddresses(
...
 			return nil
 		},
 	)
 	return result, err
 }
+
+func checkIfVMHasNICs(client Client, id VMID, retries []RetryStrategy) (bool, error) {
+	networkInterfaces, err := client.ListNICs(id, retries...)
+	if err != nil {
+		return false, nil
```
Comment (eslutsky) [inline vm_ip_wait.go:55]: why it returns nil when an error occurs?

Comment (janosdebugs) [reply vm_ip_wait.go:55]: Because we purposefully ignore this error since the check only runs in an error case.

File: vm_ip_wait.go [hunk 2]
```diff
@@ -31,10 +42,34 @@ func waitForIPAddresses(
...
 			return nil
 		},
 	)
 	return result, err
 }
+
+func noIPAddrCheckIfVMHasNICs(client Client, id VMID, retries []RetryStrategy) (bool, error) {
+	networkInterfaces, err := client.ListNICs(id, retries...)
+	if err != nil {
+		return false, errNoIPAddressesReportedYet
```
Comment (engelmi) [inline vm_ip_wait.go:65]: Returning `errNoIPAddressesReportedYet` here obfuscates the real error and might lead to confusion later, I think. Could we wrap the error in a custom one like in line 68?

Comment (janosdebugs) [reply vm_ip_wait.go:65]: It doesn't because the `ListNICs` call is an optional helper and the failure to list the NICs doesn't really relate to the fact that no IP addresses were found. The `ListNICs` call is a debugging measure to create a more descriptive error message, and the failure is logged via the logger anyway.

**Review by engelmi — APPROVED** [review]
